---
- hosts: all
  become: yes
  tasks:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
    - copy:
           content: "your config line here"
           dest: "/tmp/test.txt"